### ISSUE TITLE
waipy Git Clone error

### ISSUE THREAD

**Issue by NWRichmond** [mabelcalim/waipy#17]
Cloning waipy through the CLI or with GitHub Desktop (tested on two separate Windows 10 machines) results in the following error: "fatal: cannot create directory at 'Waipy Examples /IpythonNotebook ': No such file or directory"

The same error is produced by issuing:
`git checkout -f HEAD`

**Comment by m-weigand** [comment]
Hi there, this is a strange issue with some spaces in the directories...

fixed here, but I need to prepare a proper merge request...

https://github.com/m-weigand/waipy/commit/a4e8d8ed2a632c8d9216a5b1293eaaa6a9d5a76e
