### ISSUE TITLE
Power is plotted in log2

### ISSUE THREAD

**Issue by m-weigand** [mabelcalim/waipy#18]
The Wavelet power plotted using the contourf function is converted to log2 before plotting. Why do we do this?

**Comment by mabelcalim** [comment]
Hi, it is convenient to write the scales as fractional power of two.  This suggestion can be seen in Torrence and Compo (1998) "The pratical guide to wavelet analysis" (available here : http://paos.colorado.edu/research/wavelets/bams_79_01_0061.pdf). Please check section3f of this paper for more information.
