### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by syedhamidali** [mabelcalim/waipy#25]
![image](https://user-images.githubusercontent.com/35923822/121476327-270fb780-c9e4-11eb-91cb-bdf1384f171e.png)

**Comment by Semirarmis** [comment]
Same error here :/

**Comment by GallowayJ** [comment]
@syedhamidali Please could you close this issue? I've opened a new issue referencing this one with what I think is root cause.

**Comment by syedhamidali** [comment]
Sure
