### ISSUE TITLE
Error in sematic version number

### ISSUE THREAD

**Issue by GallowayJ** [mabelcalim/waipy#26]
https://github.com/mabelcalim/waipy/blob/9b396cb216cbb2e3e0e4fc55c0dd6b6718768d56/lib/waipy/__init__.py#L34

@mabelcalim Could you change this to from  '0.0.1.51' to  '0.1.51'? `Pip` (and perhaps the tool used to mirror waipy on PyPi?) are getting confused an think that the current version  '0.0.1.51' is older than '0.0.9.0' as 9 > 1.

This is indirectly leads to this [issue](https://github.com/mabelcalim/waipy/issues/25) as `pip install waipy` installs 0.0.9.0 which throw an indentation error on `import waipy`.

**Comment by mabelcalim** [comment]
Hi GallowayJ,

Sorry it took me so long to respond this issue. A new package is uploaded in Pipit, just. now. Thanks for your contribution and patience.
Mabel.

**Comment by GallowayJ** [comment]
Thank you for creating and sharing waipy! @mabelcalim
