### ISSUE TITLE
how to change the cmap in waipy ?

### ISSUE THREAD

**Issue by Akshayksagar** [mabelcalim/waipy#28]
Hey, its a great package . But i am unable to change cmap from viridis to jet or other. I have gone through main package script, i have made changes there but still unable to do that. please help.
thanks and regards 
Akshay

**Comment by mabelcalim** [comment]
Hi Akshayksagar,

Try to use [waipy_prêt-à-porter](https://github.com/mabelcalim/waipy/blob/master/examples/waipy_prêt-à-porter.ipynb) in the examples. There you can change whatever you wanted in waipy ;) 
Downloaded as ipynb and change it  ;) 
I hope this message helps.
Best
Mabel
