### ISSUE TITLE
wavelet coherence issue

### ISSUE THREAD

**Issue by nelerey** [mabelcalim/waipy#8]
There is some problem with the calculation of the wavelet coherence in the function cross_wavelet. When applying plot_cohere in "Example 2 random signals" as follows:
```
import waipy
import numpy as np

x = np.linspace(0,100,100)
y1 = np.random.rand(100)  # Generation of the Random Signal 1
y2 = np.random.rand(100)  # Generation of the Random Signal 2
#print x
data_norm = waipy.normalize(y1)
data_norm1 = waipy.normalize(y2)

result = waipy.cwt(data_norm, 1, 1, 0.25, 2, 4/0.25, 0.72, 6, mother='Morlet',name='x')
result1 = waipy.cwt(data_norm1, 1, 1, 0.25, 2, 4/0.25, 0.72, 6, mother='Morlet',name='y')

cross_power, coherence, phase_angle = waipy.cross_wavelet(result['wave'], result1['wave'])
waipy.plot_cohere('Coherence two random signals', coherence, x, result, result1)


```

the following plot is obtained: 
![coherence x vs y](https://user-images.githubusercontent.com/33802211/36906517-68075e12-1e36-11e8-9458-57c93f7f4c9e.png)

**Comment by mabelcalim** [comment]
Hi Nele,
This issue is already fixed! Check the new waipy version and some new examples at:
https://github.com/mabelcalim/waipy/blob/master/Waipy%20Examples%20/Jupyter/cwa_changeFreq_example.ipynb

**Comment by Kangarooamso** [comment]
Hi 
On running this code;
result = waipy.cwt(data_norm, 1, 1, 0.25, 2, 4/0.25, 0.72, 6, mother='Morlet',name='x'),
the following error occurs,
/home/okama/anaconda2/lib/python2.7/site-packages/waipy/cwt/lib_wavelet.pyc in wavelet(Y, dt, mother, param)
    130                 k_neg = [e * (-1) for e in k_neg]                       # negative part
    131                 k_neg = k_neg[1:-1]                                     # delete the first value of k_neg = last value of k_pos
--> 132         k = np.concatenate((k_pos,k_neg), axis =1)                      # vector of symmetric
    133         # compute fft of the padded time series
    134         f = np.fft.fft(x,n)

AxisError: axis 1 is out of bounds for array of dimension 1

How do i solve it?
