### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by maky-hnou** [mabelcalim/waipy#9]
After I installed waipy by following what was written in the readme file, I tried to import it but I got this error : 

`$ python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 18:21:58) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import waipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hani/anaconda3/lib/python3.6/site-packages/waipy/__init__.py", line 10, in <module>
    from .cwt.lib_wavelet import `nextpow2`
  File "/home/hani/anaconda3/lib/python3.6/site-packages/waipy/cwt/lib_wavelet.py", line 48
    """CAUTION : default values"""
                                 ^
TabError: inconsistent use of tabs and spaces in indentation
`

![hhhhh](https://user-images.githubusercontent.com/24441488/38319592-0d9c62de-382a-11e8-96ca-da3b8681c0fa.png)

Did anyone face the same problem?

**Comment by SillyTurtle** [comment]
Yes I have the same problem.

**Comment by maky-hnou** [comment]
@SillyTurtle Have you any idea how to solve it?
I even tried to edit that file, but the error is still

**Comment by Lachlan00** [comment]
Hi, same issue here. 

Running Python 3.6.2 :: Anaconda custom (64-bit) and waipy 0.0.9.0

**Comment by Lachlan00** [comment]
Just had a look at the source code. For some reason the indentation for the `wave_bases()` function in `lib_wavelet.py` seems to be pretty chaotic. I think this is causing the issue.

**Comment by mabelcalim** [comment]
Hi all,

The waipy version 0.0.9.0 it's related to python2.7.
The updated version (0.0.1.4.0) it's on github (
https://github.com/mabelcalim/waipy/).
You can fork/download from github or use it without install it , please see
*waipy_prêt-à-porter.ipynb example*
<https://github.com/mabelcalim/waipy/blob/master/Waipy%20Examples%20/waipy_pr%C3%AAt-%C3%A0-porter.ipynb>



*Thanks for using waipy!*


------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------
